config/routes.rb
Rails.application.routes.draw do
	devise_for :users, path_names: { sign_in: "login", sign_out: "logout", sign_up: "signup" }

	resources :jobs do
		resources :job_apps
	end

	

	authenticated :user do
		root :to => "jobs#index", as: :authenticated_root
	end
	
	unauthenticated :user do
		root :to => "pages#home", as: :unauthenticated_root
	end
  
	match "/is/about", to: "pages#about", via: :get, as: :pages_about
  

end

app/models/application.rb
class Application < ActiveRecord::Base
	
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :jobs
end

app/models/industry.rb
class Industry < ActiveRecord::Base
	has_many :jobs
end

app/models/job.rb
	  # t.string 	:title
   #    t.text   	:description
   #    t.string 	:company
   #    t.string 	:url
   #    t.integer 	:user_id
   #    t.integer 	:parish_id
   #    t.integer 	:category_id
   #    t.integer 	:industry_id


class Job < ActiveRecord::Base
	has_many :job_apps, dependent: :destroy
	

	belongs_to :category
	belongs_to :parish
	belongs_to :industry
	belongs_to :user


	# after_create :send_notification

	def send_notification
	    JobAppMailer.new_job(self).deliver
	end

end

app/models/job_app.rb
      # t.string    :email
      # t.string    :name
      # t.string    :resumelink
      # t.string    :linkedinprofile
      # t.string    :twitterlink
      # t.string    :weblink
      # t.text      :message
      # t.integer   :user_id

      # t.boolean         :published, :default => true
      # t.references      :job, index: true
      # t.timestamps      null: false
      # add_foreign_key   :job_apps, :jobs


class JobApp < ActiveRecord::Base
  belongs_to :job
  belongs_to :user

  after_create :send_notification

  def send_notification
      JobAppMailer.new_jobapp(self).deliver
  end


end

app/models/parish.rb
class Parish < ActiveRecord::Base
	has_many :jobs

	def self.options_for_select
		order('LOWER(name)').map { |e| [e.name, e.id] }
	end
end

app/models/user.rb
  	  # t.string :email,              null: false, default: ""
      # t.string :encrypted_password, null: false, default: ""

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

         
  has_many :jobs
  has_many :job_apps
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/job_apps_controller.rb
class JobAppsController < ApplicationController
	before_filter :authenticate_user!

	def create
		@job = Job.find(params[:job_id])
		@new_jobapp = @job.job_apps.create(params.require(:job_app).permit(
			:email,
			:name,
			:resumelink,
			:linkedinprofile,
			:twitterlink,
			:weblink,
			:message
			))
		
		redirect_to job_path(@job)
		# flash.now[:notice] = "Your application was successfully sent (Y)"
	end


	# def new
	# 	@jobapp = current_user.job_apps.build
	# end


	def destroy
		@job = Job.find(params[:job_id])
		@jobapp = @job.job_apps.find(params[:id])
		@jobapp.destroy

		redirect_to job_path(@job)
		
	end

end

app/controllers/jobs_controller.rb
require 'builder'
include ActionView::Helpers::NumberHelper


class JobsController < ApplicationController
	before_filter :authenticate_user!, except: [ :index, :show ]
	before_action	:find_job, only: [:show, :edit, :update, :destroy]
	
	def index
		if params[:category].blank? && params[:parish].blank?
			@jobs = Job.all.order("created_at DESC")
		elsif params[:category].blank? && !params[:parish].blank?
			@parish_id = Parish.find_by(name: params[:parish]).id
			@jobs = Job.where(parish_id: @parish_id).order("created_at DESC")
		elsif params[:parish].blank? && !params[:category].blank?
			@category_id = Category.find_by(name: params[:category]).id
			@jobs = Job.where(category_id: @category_id).order("created_at DESC")
		elsif !params[:parish].blank? && !params[:category].blank?
			@category_id = Category.find_by(name: params[:category]).id
			@parish_id = Parish.find_by(name: params[:parish]).id
			@jobs = Job.find(whatever).includes(:category, :parish).order("created_at DESC")
		end
	end

	def show
	end

	def new
		@job = current_user.jobs.build
	end

	def create
		@job = current_user.jobs.build(jobs_params)

		if @job.save
			redirect_to @job, notice: "Vacancy has been successfully created."
		else
			render "New"
		end	
	end

	def edit
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job, notice: "Vacancy has been successfully upated."
		else
			render	"Edit"
		end
	end

	def destroy
		@job.destroy
		redirect_to root_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url, :category_id, :parish_id, :industry_id)
	end

	def find_job
		@job = Job.find(params[:id])
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	# layout "fullwidth", except: [:index, :faqs]



	def home
		
	end

	def about
	 	# Render this action with specific layout
	    # render layout: "popout"
	    #renders with views/layouts/popout.html.erb
	end

	def faq
	end

	def pricing
		
	end

	def presspackage
		
	end

	def survey
		
	end

	def terms
		
	end

	def privacypolicy
		
	end

	def partners
		
	end

	def careers
		
	end

	def advice
		
	end

	def media
		
	end

	def team
		
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_apps_helper.rb
module JobAppsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/job_apps/_form.html.haml
= simple_form_for([@job, @job.job_apps.build], html: { class: 'form-horizontal'}) do |f|
	= f.input :name, label: "Full Name", input_html: { class: "form-control" }
	= f.input :email, label: "Your Email", input_html: { class: "form-control" }
	= f.input :resumelink, label: "Link to Resume", input_html: { class: "form-control" }
	= f.input :linkedinprofile, label: "LinkedIn Profile URL", input_html: { class: "form-control" }
	= f.input :twitterlink, label: "Twitter Profile URL", input_html: { class: "form-control" }
	= f.input :weblink, label: "Other Website ( Your Blog maybe )", input_html: { class: "form-control" }
	= f.input :message, label: "Cover Letter / Message", input_html: { class: "form-control" }
	%br/
	= f.button :submit, "SUBMIT APPLICATION", input_html: { class: "form-control" }

app/views/job_apps/_job_app.html.haml
.jobapp.clearfix
	.jobapp_cotent
		%p.jobapp_name
			= job_app.name
		%p.jobapp_email
			= job_app.email
		%p.jobapp_resumelink
			= job_app.resumelink
		%p.jobapp_linkedinprofile
			= job_app.linkedinprofile
		%p.jobapp_twitter
			= job_app.twitterlink
		%p.jobapp_weblink
			= job_app.weblink
		%p.jobapp_message
			= job_app.message

	%p= link_to "Delete", [job_app.job, job_app], method: :delete,data: { confirm: "Are you sure?" }, class: "btn btn-small btn-default"

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: { class: 'form-horizontal'}) do |f|
	= f.collection_select :category_id, Category.all, :id, :name, {promt: "Please choose a category."}, input_html: { class: "dropdown-toggle" }
	= f.collection_select :parish_id, Parish.all, :id, :name, {promt: "Please choose a parish."}, input_html: { class: "dropdown-toggle" }
	= f.collection_select :industry_id, Industry.all, :id, :name, {promt: "Please choose an industry."}, input_html: { class: "dropdown-toggle" }
	= f.input :title, label: "Job Title", input_html: { class: "form-control" }
	= f.cktext_area :description, label: "Job Description", input_html: { class: "form-control" }
	= f.input :company, label: "Your Company", input_html: { class: "form-control" }
	= f.input :url, label: "Link to Job", input_html: { class: "form-control" }
	%br/
	= f.button :submit

app/views/jobs/_list.html.haml
#jobs
	- @jobs.in_groups_of(1, false) do |jobgroup|
		.jobgroup.col-lg-3.col-md-3.col-sm-6.col-xs-12
			- jobgroup.each do |job|
				.job
					%h4= link_to job.title, job
					%p= job.parish.name
					%p= job.company
					%p= job.user.email

app/views/jobs/edit.html.haml
= provide(:title, "Anziel - Edit Job")
%h2 Edit Job

= render 'form'

= link_to "Back", authenticated_root_path, class: "btn btn-small btn-default"

app/views/jobs/index.html.haml
= provide(:title, "Anziel")
/ #jobs
/ 	- @jobs.in_groups_of(1, false) do |jobgroup|
/ 		.jobgroup.col-lg-3.col-md-3.col-sm-6.col-xs-12
/ 			- jobgroup.each do |job|
/ 				.job
/ 					%h4= link_to job.title, job
/ 					%p= job.parish.name
/ 					%p= job.company


%nav.navbar.navbar-default
	.container
		%ul.nav.navbar-nav
			- Category.all.each do |category|
				%li= link_to category.name, jobs_path(category: category.name)
			.navbar-text.navbar-right.navbar-link.rgt= link_to "Post a Job", new_job_path
			
			/ %select.form-control
		%ul.nav.navbar-nav
			- Parish.all.each do |parish|
				%li= link_to parish.name, jobs_path(parish: parish.name)

= render 'list'

app/views/jobs/new.html.haml
= provide(:title, "Anziel - New Job")
%h1 New Job

= render 'form'

= link_to "Back", authenticated_root_path, class: "btn btn-small btn-default"

app/views/jobs/show.html.haml
= provide(:title, "Anziel - Job Info") 
#jobs
	.job
		%h2= @job.title
		%p= @job.description.html_safe
		%p= @job.company
		%p= link_to @job.company, @job.url, target: '_blank'
%br
%hr
%br
#links
	= link_to "Back", authenticated_root_path, class: "btn btn-small btn-default"
	= link_to "Edit", edit_job_path(@job), class: "btn btn-small btn-default"
	= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-small btn-default"

%br
%hr
%br
#jobapplications
	= @job.job_apps.count
	Applications

	= render @job.job_apps
	%h2= "Apply for this job"
	= render 'job_apps/form', new_jobapp: @new_jobapp

app/views/layouts/application.html.haml
!!!
%html
%head
	%title= yield (:title)
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
		
	- if notice
		#notice_wrapper
			%p.notice
				= notice
	- elsif alert
		#notice_wrapper
			%p.alert
				= alert

	%header
		#header
			.site-links
				%nav.navbar.navbar-default
					.navbar-header

						- if user_signed_in?
							%btn.navbar-toggle.collapsed{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}= link_to "Log Out", destroy_user_session_path, :method => :delete
						- else
							%btn.navbar-toggle.collapsed{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}= link_to "Sign In", new_user_session_path
						.logo.navbar-brand
							= link_to "Anziel", authenticated_root_path
					.navbar-collapse.collapse
						%ul.nav.navbar-nav.navbar-right
							%li= link_to "About Us", pages_about_path
							%li= link_to "FAQ", '#'

							- if user_signed_in?
								%li
									%a= current_user.email
								%li= link_to "Edit Profile", edit_user_registration_path
								%li= link_to "Log Out", destroy_user_session_path, :method => :delete
							- else
								%li= link_to "Sign Up", new_user_registration_path
								%li= link_to "Log In", new_user_session_path
						
	.container
		.row
			= yield

	%footer
		.border-top#social-footer
			.containter
				.row
					.col-lg-4.col-md-12.col-sm-12.col-xs-12
						= link_to 'https://www.twitter.com/anzielhq', target: '_blank', class: 'box-link twitter' do
							%span.light What's new?
							%span.headline.bold Follow us on Twitter
					.col-lg-4.col-md-12.col-sm-12.col-xs-12
						= link_to 'https://www.facebook.com/anzielhq', target: '_blank', class: 'box-link facebook' do
							%span.light Get the latest
							%span.headline.bold Like us on facebook
					.col-lg-4.col-md-12.col-sm-12.col-xs-12
						= link_to 'https://www.anziel.com/newsletter', class: 'box-link newsletter' do
							%span.light Be inspired
							%span.headline.bold Subscribe to our Newsletter
		.border-top#-footer
			.containter
				.row
					.col-lg-4.col-md-12.col-sm-12.col-xs-12
						=link_to "Pricing", '#'
						%br
						=link_to "Brand", '#'
						%br
						=link_to "Press Package", '#'
						%br
						=link_to "Answer our Anonymous Survey", '#'
					.col-lg-4.col-md-12.col-sm-12.col-xs-12
						=link_to "Blog", '#'
						%br
						=link_to "Media", '#'
						%br
						=link_to "Advice & Tips", '#'
					.col-lg-4.col-md-12.col-sm-12.col-xs-12
						=link_to "Terms", '#'
						%br
						=link_to "Privacy Policy", '#'
						%br
						=link_to "Partners & Friends", '#'
					

app/views/pages/home.html.haml
Hello there. This is the new home page